package jlu.kemiko.libman.ui.theme

import androidx.compose.ui.graphics.Color

// Light palette
val md_theme_light_primary = Color(0xFF2F4EB3)
val md_theme_light_onPrimary = Color(0xFFFFFFFF)
val md_theme_light_primaryContainer = Color(0xFFD8E2FF)
val md_theme_light_onPrimaryContainer = Color(0xFF001A4D)
val md_theme_light_secondary = Color(0xFF56617A)
val md_theme_light_onSecondary = Color(0xFFFFFFFF)
val md_theme_light_secondaryContainer = Color(0xFFD9E2FF)
val md_theme_light_onSecondaryContainer = Color(0xFF101A2C)
val md_theme_light_tertiary = Color(0xFF19645B)
val md_theme_light_onTertiary = Color(0xFFFFFFFF)
val md_theme_light_tertiaryContainer = Color(0xFFAEEDE0)
val md_theme_light_onTertiaryContainer = Color(0xFF00201A)
val md_theme_light_error = Color(0xFFBA1A1A)
val md_theme_light_onError = Color(0xFFFFFFFF)
val md_theme_light_errorContainer = Color(0xFFFFDAD6)
val md_theme_light_onErrorContainer = Color(0xFF410002)
val md_theme_light_background = Color(0xFFFDF8F3)
val md_theme_light_onBackground = Color(0xFF1B1B1F)
val md_theme_light_surface = Color(0xFFFDF8F3)
val md_theme_light_onSurface = Color(0xFF1B1B1F)
val md_theme_light_surfaceVariant = Color(0xFFE1E2EC)
val md_theme_light_onSurfaceVariant = Color(0xFF44474F)
val md_theme_light_outline = Color(0xFF747783)
val md_theme_light_outlineVariant = Color(0xFFC5C6D0)
val md_theme_light_inverseSurface = Color(0xFF303034)
val md_theme_light_inverseOnSurface = Color(0xFFF3F0F6)
val md_theme_light_inversePrimary = Color(0xFFAEC6FF)
val md_theme_light_scrim = Color(0xFF000000)

// Dark palette
val md_theme_dark_primary = Color(0xFFAEC6FF)
val md_theme_dark_onPrimary = Color(0xFF001D55)
val md_theme_dark_primaryContainer = Color(0xFF11358C)
val md_theme_dark_onPrimaryContainer = Color(0xFFD8E2FF)
val md_theme_dark_secondary = Color(0xFFBEC7DC)
val md_theme_dark_onSecondary = Color(0xFF253042)
val md_theme_dark_secondaryContainer = Color(0xFF3C475A)
val md_theme_dark_onSecondaryContainer = Color(0xFFDAE2F9)
val md_theme_dark_tertiary = Color(0xFF7BD0C4)
val md_theme_dark_onTertiary = Color(0xFF003732)
val md_theme_dark_tertiaryContainer = Color(0xFF005046)
val md_theme_dark_onTertiaryContainer = Color(0xFFAEEDE0)
val md_theme_dark_error = Color(0xFFFFB4AB)
val md_theme_dark_onError = Color(0xFF690005)
val md_theme_dark_errorContainer = Color(0xFF93000A)
val md_theme_dark_onErrorContainer = Color(0xFFFFDAD6)
val md_theme_dark_background = Color(0xFF121317)
val md_theme_dark_onBackground = Color(0xFFE3E2E8)
val md_theme_dark_surface = Color(0xFF121317)
val md_theme_dark_onSurface = Color(0xFFE3E2E8)
val md_theme_dark_surfaceVariant = Color(0xFF45464F)
val md_theme_dark_onSurfaceVariant = Color(0xFFC5C6D0)
val md_theme_dark_outline = Color(0xFF8F909A)
val md_theme_dark_outlineVariant = Color(0xFF45464F)
val md_theme_dark_inverseSurface = Color(0xFFE3E2E8)
val md_theme_dark_inverseOnSurface = Color(0xFF29292E)
val md_theme_dark_inversePrimary = Color(0xFF2F4EB3)
val md_theme_dark_scrim = Color(0xFF000000)

// Extended role colors shared across schemes
val successLight = Color(0xFF2E7D32)
val onSuccessLight = Color(0xFFFFFFFF)
val successContainerLight = Color(0xFFC9F7D5)
val onSuccessContainerLight = Color(0xFF0C3B16)
val warningLight = Color(0xFFB55400)
val onWarningLight = Color(0xFFFFFFFF)
val warningContainerLight = Color(0xFFFFDDB5)
val onWarningContainerLight = Color(0xFF361900)
val infoLight = Color(0xFF1565C0)
val onInfoLight = Color(0xFFFFFFFF)
val infoContainerLight = Color(0xFFD5E3FF)
val onInfoContainerLight = Color(0xFF001B3F)

val successDark = Color(0xFF7FDB88)
val onSuccessDark = Color(0xFF003911)
val successContainerDark = Color(0xFF11531E)
val onSuccessContainerDark = Color(0xFFC9F7D5)
val warningDark = Color(0xFFFFB869)
val onWarningDark = Color(0xFF502400)
val warningContainerDark = Color(0xFF713600)
val onWarningContainerDark = Color(0xFFFFDDB5)
val infoDark = Color(0xFFA9C7FF)
val onInfoDark = Color(0xFF002F68)
val infoContainerDark = Color(0xFF00468F)
val onInfoContainerDark = Color(0xFFD5E3FF)